<a href="https://colab.research.google.com/github/belikeamitesh/CS306-Machine-Learning/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML Lab (CS360)
# Assignment 1

## PART 1: NumPy Basic

1. Write a NumPy program to create an array of 10 zeros,10 ones,
10 fives

In [ ]:
import numpy as np

zeros = np.zeros(10,dtype=int)
# print(zeros)

ones = np.ones(10,dtype=int)
# print(ones)

fives = np.ones(10,dtype=int)*5
# print(fives)

ans = np.concatenate((zeros,ones,fives))
print(ans)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


2. Write a NumPy program to create an array of all the even
integers from 10 to 50

In [ ]:
evenarray = np.arange(21, 51, 21)
print(evenarray)

[21 42]


3. Write a NumPy program to generate a random number between 0 and
1

In [ ]:
# random_value_matrix=np.random.rand((3,3))
# print(random_value_matrix)
random_num=np.random.rand()
print(random_num)

0.46381354060838254


4. Write a NumPy program to save the matrix (generated in question
3) to a text file and load it

In [ ]:

random_value_matrix = np.random.rand(3, 3)

print(random_value_matrix)
print("\n")

#saving to txt file
np.savetxt("matrix.csv", random_value_matrix)

print("Saved Matrix is Loaded : ")
#Loading from txt file
random_value_matrix = np.loadtxt("matrix.csv")
print(random_value_matrix)

[[0.51945911 0.21189405 0.52169238]
 [0.03588986 0.66339998 0.58454832]
 [0.41053641 0.65817781 0.16360751]]


Saved Matrix is Loaded : 
[[0.51945911 0.21189405 0.52169238]
 [0.03588986 0.66339998 0.58454832]
 [0.41053641 0.65817781 0.16360751]]


# Part 2 : Pandas Excel

1. Write a python program to read an image and save the image as a
matrix to a .csv file using pandas

In [ ]:
import pandas as pd
import matplotlib.image as img

#Getting image from link
# !wget -P ./ https://blognumbers.files.wordpress.com/2010/09/6.jpg


# reading imagea as an array
image = img.imread('6.jpg')
print("Original Image Shape : ",image.shape)

#if image is colored(RGB)
if(image.shape[2]==3):

  img1 = image.reshape(image.shape[0],-1)
  print("Original Image 2D Shape : ",img1.shape)

# grayscale image
else:
  # remain as it is
  img1=image

#converting to dataframe
df = pd.DataFrame(data = img1)

#exporting dataframe to CSV file
df.to_csv("img.csv",header=None,index=None)

loaded_df = pd.read_csv('img.csv',header=None) 

# print(loaded_df)

# getting matrices values
values_loadeddf= loaded_df.values

#reshaping to 3D matrix
ans = values_loadeddf.reshape(values_loadeddf.shape[0],values_loadeddf.shape[1] // image.shape[2],image.shape[2])
print("Shape of Loaded Image : ",ans.shape)

# print(df)

Original Image Shape :  (1024, 791, 3)
Original Image 2D Shape :  (1024, 2373)
Shape of Loaded Image :  (1024, 791, 3)


2. Write a program to import excel data from the .csv file
(generated in question 1) by excluding the last row and last
column

In [ ]:
# Importing excel data(data frame) from .csv file (generated in Q1)
read_df = pd.read_csv('img.csv',header=None)

df=pd.DataFrame(data=read_df)

# Excluding last row and last column
new_df= df.iloc[:-1,:-1]
# print(new_df)
print("Loaded Image Shape after excluding last row and column : ",new_df.shape)

      0     1     2     3     4     5     ...  2366  2367  2368  2369  2370  2371
0      255   255   255   255   255   255  ...   255   255   255   255   255   255
1      255   255   255   255   255   255  ...   255   255   255   255   255   255
2      255   255   255   255   255   255  ...   255   255   255   255   255   255
3      255   255   255   255   255   255  ...   255   255   255   255   255   255
4      255   255   255   255   255   255  ...   255   255   255   255   255   255
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
1018   255   255   255   255   255   255  ...   255   255   255   255   255   255
1019   255   255   255   255   255   255  ...   255   255   255   255   255   255
1020   255   255   255   255   255   255  ...   255   255   255   255   255   255
1021   255   255   255   255   255   255  ...   255   255   255   255   255   255
1022   255   255   255   255   255   255  ...   255   255   255   255   255   255

[1023 rows x 23

3. Write a Pandas program to create the today's date

In [ ]:
todaydate= pd.to_datetime("today")
print("Today's date: " ,todaydate.date())

Today's date: 2021-08-09


# Part 3

1. Create a mini calculator to know the age of a person after
putting the range (i.e. date of birth and current date)

In [ ]:
import datetime

def age_calculator(dob):
  # today = pd.to_datetime("today")
  today=datetime.datetime.now()
  return today.year - birthdate.year - ((today.month, today.day) < (birthdate.month, birthdate.day))

birthdate_year = int(input("Enter your birth year: "))
birthdate_month = int(input("Enter your birth month: "))
birthdate_day = int(input("Enter your birthdate day: "))
birthdate = datetime.datetime(birthdate_year, birthdate_month, birthdate_day)

print("You are ",age_calculator(birthdate)," years old !")

Enter your birth year: 2000
Enter your birth month: 5
Enter your birthdate day: 12
You are  21  years old !
